apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: angular-app
  name: angular
spec:
  type: ClusterIP
  ports:
    - name: angular
      port: 4200
      protocol: TCP
  selector:
    deployment-label-key: deployment-label-value
